# /* eslint-disable */
name: catalogue-meta-schema-check
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check-catalogue-meta-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
         persist-credentials: false
      - name: Install pnpm
        run: npm install -g pnpm --force
      - name: Setup pnpm global bin
        run: pnpm setup
      - name: Install NX CLI
        run: pnpm add -g nx
      - name: Install and build ğŸ”§
        run: |
          pnpm install --frozen-lockfile
          nx run-many -t build-catalogue-meta
